project: #项目信息
 name: message-demo
  
spring: #应用配置
  application:
    name: ${project.name}
    
master: #主数据库配置
 db:
  type: mysql
  url: jdbc:mysql://vcc.hbasesoft.com:8306/sgp_msg?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
  username: sgp
  password: sgp
    
cache: #缓存配置
  model: REDIS
  redis:
    address: 127.0.0.1:6379
    
job:
  register:
    url: localhost:2181
    namespace: framework-message-demo
  event:
    enable: false

message: #消息服务
  model: REDIS
  redis:
   address: 127.0.0.1:6379
   broadcast:
    channels: log-p21
  executor: # 事件执行者性能配置
   memeryCapacity: 10  # 缓冲在内存中最大容量
   coreSize: 1 # 设置核心线程数量
   keepAliveSeconds: 600 # 允许的空闲时间
   maxPoolSize: 10 # 线程池维护线程的最大数量
   queueCapacity: 10 # 线程缓冲最大容量，该值要大于等于memeryCapacity
   
#message: #消息服务
#  model: ROCKET_MQ
#  rocketmq:
#    namesrvAddr: 192.168.99.100:9876
#    producer:
#    consumer:
#      consumerBatchMaxSize: 0
#      isEnableOrderConsumer: false
#      isEnableHisConsumer: false
#  executor: # 事件执行者性能配置
#   coreSize: 20 # 设置核心线程数量
#   maxPoolSize: 64 # 线程池维护线程的最大数量

   
    